owner: amblerapp
repo: status-discord

sites:
  - name: MonitoRSS-Ambler
    url: https://monitorss.ambler.app/
  - name: MonitoRSS-Ambler (Render)
    url: $MONITORSS_AMBLER_RENDER
  - name: MonitoRSS-Cord
    url: https://monitorss.cord.town/
  - name: MonitoRSS-Cord (Render)
    url: $MONITORSS_CORD_RENDER
  - name: MonitoRSS-Music
    url: https://music-rss.cord.town/
  - name: MonitoRSS-Music (Render)
    url: $MONITORSS_MUSIC_RENDER
  - name: MonitoRSS-Tech
    url: https://tech-rss.cord.town/
  - name: MonitoRSS-Tech (Render)
    url: $MONITORSS_TECH_RENDER

status-website:
  cname: discord.status.ambler.app
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Discord Bots Status | Ambler App
  introTitle: "**Upptime** for Discord Bots"
  introMessage: 디스코드 봇 모니터
